set(CPACK_PACKAGE_NAME "opc-server")
set(CPACK_PACKAGE_VENDOR "OPC_SERVER contributors")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Industrial Modbus to OPC UA gateway")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME
  "opc-server-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_GENERATOR "TGZ")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES
  "/build/"
  "/\\.git/"
  "/dist/"
  "/stage/"
)

include(CPack)
